global:
  resolve_timeout: 5m

route:
  group_by: ['example']
  group_wait: 10s
  group_interval: 10s
  repeat_interval: 10s
  receiver: 'email'

receivers:
- name: 'email'
  email_configs:
  - to: 'sinkwoyin@gmail.com'
    from: 'sinkwoyin@gmail.com'
    smarthost: smtp.gmail.com:587
    auth_username: 'sinkwoyin@gmail.com'
    auth_identity: 'sinkwoyin@gmail.com'
    auth_password: 'Jt27435781'

inhibit_rules:
  - source_match:
      severity: 'critical'
    target_match:
      severity: 'warning'
    equal: ['alertname', 'dev', 'instance']